image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
environment:
  site: your-usernamelouden
- package: |
    cd $site
    ./build.sh
    tar -cvz public > ../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz