url:        	"http://jefflouden.com/"
permalink:      ":title/"
exclude:        ["README.md", "CNAME"]
owner-name:     "Jeffrey Louden"
owner-page:     "http://jefflouden.com/"
owner-email:    "jeff@jefflouden.com"
plugins:        "./_plugins"
pygments:       true
topic_list:     ["articles"]
name:           "Jeffrey Louden"
license:        "Creative Commons Attribution-Share Alike 3.0 United States License."
domain:         localhost
port:           4000

excerpt_separator: ""