url:        	"https://jefflouden.com"
permalink:      ":title/"
exclude:        ["README.md", "CNAME", "*.sass", "node_modules", "Gruntfile.js", "package.json", "bower.json", "Gemfile"]
owner-name:     "Jeffrey Louden"
owner-page:     "https://jefflouden.com/"
owner-email:    "jeff@jefflouden.com"
topic_list:     ["articles"]
name:           "Jeffrey Louden"

excerpt_separator: ""

sass:
    style: :compressed
