url: 'https://jefflouden.com'
exclude: ['README.md', 'CNAME', 'Gemfile']
owner-name: 'Jeffrey Louden'
owner-page: 'https://jefflouden.com/'
owner-email: 'jeff@jefflouden.com'
title: 'Jeffrey Louden'

excerpt_separator: ''
