url: "https://jefflouden.com"
permalink: ":title/"
exclude:
  [
    "README.md",
    "CNAME",
    "*.sass",
    "node_modules",
    "package.json",
    "bower.json",
    "Gemfile",
    ]
owner-name: "Jeffrey Louden"
owner-page: "https://jefflouden.com/"
owner-email: "jeff [at] jefflouden [dot] com"
topic_list: ["articles"]
title: "Jeffrey Louden"

excerpt_separator: ""

sass:
  style: :compressed
