auto:           true
baseurl:        "/"
permalink:      "/:categories/:title/"
paginate:       1000
pygments:       true
exclude:        ["README.md", "CNAME"]
owner-name:     "Jeffrey Louden"
owner-page:     "http://jefflouden.com/"
owner-email:    "jeff@jefflouden.com"
plugins:        "./_plugins"
topic_list:     ["articles"]
name:           "jefflouden.com"
license:        "Creative Commons Attribution-Share Alike 3.0 United States License."
static_url:     "/static"
lsi:            true
domain:         localhost
port:           4000