author: "Jeffrey Louden"
title: "Jeffrey Louden"
description: "Technology Lead at The New Yorker and former Lead Developer at Obama for America based in New York, NY."

twitter_handle: "@jeffreylouden"