author: "Jeffrey Louden"
title: "Jeffrey Louden"
description: "Web Developer at @google. Formerly of The New Yorker, Obama for America, and Apple. San Francisco, CA."

twitter_handle: "@jeffreylouden"
