author: "Jeffrey Louden"
title: "Jeffrey Louden"
description: "Director of Technology at The New York Times. Formerly Google, The New Yorker, Obama for America, and Apple."
twitter_handle: "@jeffreylouden"
