author: "Jeffrey Louden"
title: "Jeffrey Louden"
description: "Mission-driven Engineering leader. Vice President of Software Engineering at Time, Inc. Formerly Lyft, The New York Times, Google, The New Yorker, Obama for America, and Apple."
