name: (Re)generate entries
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build.sh
      - name: Auto committing (re)generated) files
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: "chore: auto-commit"
          branch: ${{ github.ref }}
