name: (Re)generate entries
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build.sh
  minify_and_commit:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1
      - name: Auto committing (re)generated) files
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: "chore: auto-commit"
          branch: ${{ github.ref }}
