name: Minify
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
